version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - err113
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - funcorder
    - gochecknoglobals
    - gomodguard
    - gosec
    - iface
    - inamedparam
    - ireturn
    - mnd
    - modernize
    - nlreturn
    - noctx
    - noinlineerr
    - nonamedreturns
    - perfsprint
    - unparam
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    funlen:
      lines: 87
      statements: 61
      ignore-comments: true
    gocritic:
      disabled-checks:
        - importShadow
        - sloppyReassign
        - unnamedResult
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    lll:
      line-length: 130
    nestif:
      min-complexity: 9
    revive:
      rules:
        - name: indent-error-flow
        - name: use-any
    staticcheck:
      checks:
        - all
        - -ST1000
    tagliatelle:
      case:
        rules:
          json: pascal
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
      - part1/
      - part2/
      - part3/
      - part4kv/
      - part5kv/
      - internal/_init/
      - .*_test.go$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
